# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bdcjy5eSsuVuDbKmLtNAWpqzJPxqLxKj
"""

import pandas as pd

# Load Dataset
df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

# Convert Order_Date to Date Format
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

# KPI Analysis
total_sales = df["Total_Sales"].sum()
total_orders = df["Order_ID"].nunique()
total_customers = df["Customer_ID"].nunique()
average_sales = df["Total_Sales"].mean()

print("Total Sales:", total_sales)
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)
print("Average Sales:", average_sales)

# Top 10 Products
top_products = df.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False)
print(top_products.head(10))

# Sales by Category
category_sales = df.groupby("Category")["Total_Sales"].sum()
print(category_sales)

# Sales by City
city_sales = df.groupby("City")["Total_Sales"].sum().sort_values(ascending=False)
print(city_sales)

# Sales by Gender
gender_sales = df.groupby("Gender")["Total_Sales"].sum()
print(gender_sales)

# Monthly Sales
df["Month"] = df["Order_Date"].dt.to_period("M")
monthly_sales = df.groupby("Month")["Total_Sales"].sum()
print(monthly_sales)

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

category_sales = df.groupby("Category")["Total_Sales"].sum()

plt.bar(category_sales.index, category_sales.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

gender_sales = df.groupby("Gender")["Total_Sales"].sum()

plt.pie(gender_sales.values, labels=gender_sales.index, autopct="%1.1f%%")
plt.title("Sales by Gender")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Month"] = df["Order_Date"].dt.to_period("M").astype(str)

monthly_sales = df.groupby("Month")["Total_Sales"].sum()

plt.plot(monthly_sales.index, monthly_sales.values, marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

city_sales = df.groupby("City")["Total_Sales"].sum().sort_values()

plt.barh(city_sales.index, city_sales.values)
plt.title("Sales by City")
plt.xlabel("Total Sales")
plt.ylabel("City")
plt.show()